name: Deploy Project
on: [push, workflow_dispatch]
env:
  MONGODB_DB_NAME: gha-demo
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Lint
        id: run-lint-id
        run: npm run lint
      - name: Run Condition If fail
        if: steps.run-lint-id.outcome == 'failure'
        run: echo "Executed in case of fail..."

  test:
    runs-on: ubuntu-latest
    environment: testing
    env:
      MY_ENV_TEST: "Testing the envirnment"
      MY_REPOSITORY_SECRET: ${{secrets.MY_REPOSITORY_SECRET}}
      MY_SECRET_BY_ENV: ${{secrets.MY_SECRET_BY_ENV}}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test.json
      - name: Use ENV
        run: | 
          echo "Here is it:" $MY_ENV_TEST
          echo "Here is it (env.MY_ENV_TEST):" ${{env.MY_ENV_TEST}}
          echo "Here is it (env.MY_REPOSITORY_SECRET):" ${{env.MY_REPOSITORY_SECRET}}
          echo "Here is it (env.MY_SECRET_BY_ENV):" ${{env.MY_SECRET_BY_ENV}}
  deploy:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      my-script-file: ${{ steps.my-publish.outputs.my-script-file }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run Build
        run: npm run build
      - name: Publish JS filename
        id: my-publish
        run: find dist/assets/*.js -type f -execdir echo 'my-script-file={}' >> $GITHUB_OUTPUT ';'
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-dist-file
          path: dist
      - name: Use ENV
        run: |
          echo "Here is it:" ${{env.MONGODB_DB_NAME}}
          echo "Here is it:" $MONGODB_DB_NAME
  download:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: my-dist-file
      - name: Output contents
        run: ls
      - name: Output filename
        run: echo "${{ needs.deploy.outputs.my-script-file }}"
      - name: Deploy
        run: echo "Deploying..."
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github context
        run: echo "${{ toJSON(github) }}"
